name: Build mkdocs and deploy to GitHub Pages

on:
   push:
     paths:
       - '**.md'

jobs:

   build:
     name: Build docs
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: ./students/k33401/Kobelev_Lev/docs
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v4
         with:
           python-version: 3.x
       - uses: actions/cache@v3
         with:
           key: ${{ github.ref }}
           path: .cache
       - run: pip install -r requirements.txt
       - run: mkdocs build

   deploy:
     if: github.event_name == 'push' && contains(fromJson('["refs/heads/master", "refs/heads/main"]'), github.ref)
     needs: build
     name: Deploy docs
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: ./students/k33401/Kobelev_Lev/docs
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: '0'
       - uses: actions/setup-python@v4
         with:
           python-version: 3.x
       - uses: actions/cache@v3
         with:
           key: ${{ github.ref }}
           path: .cache
       - run: pip install -r requirements.txt
       - run: mkdocs gh-deploy --force
